project:
  type: book

book:
  title: "BOOK"
  author: "Louis Moresi"
  date: "06/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - Notebooks/TestNB1.ipynb
    - Notebooks/TestQMD_NB1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



