project:
  type: book

book:
  title: "BOOK"
  author: "Louis Moresi"
  date: "06/03/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices:
    - Notebooks/TestNB1.ipynb
    - Notebooks/TestQMD_NB1.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-QuartoBook/HEAD?labpath=Notebooks%2FBinderLandingPage.qmd
    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-QuartoBook
  
  pdf:
    documentclass: scrreprt



