# Conda Environment for python packages etc

name: emsc_basics
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mpmath<=1.3
  - mesalib
  - numpy
  - scipy
  - h5py
  - sympy
  - pytest
  - pyvista # flagged in some tests 
  - pip
  - pip:  
    - gmsh
    - jupyter-lab>=4.1
    - jupytext>=1.16.1
